// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzLnyzE2hYDzmtE749vvVuJJCCLrzL-Uo',
    appId: '1:625297648979:web:daa23732fb9667882d85a6',
    messagingSenderId: '625297648979',
    projectId: 'adroit-hall-451612-t1',
    authDomain: 'adroit-hall-451612-t1.firebaseapp.com',
    storageBucket: 'adroit-hall-451612-t1.firebasestorage.app',
    measurementId: 'G-Q0ZLSFMBBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcZ_-dg0L2hEhZVCGCXyod8XuQBQYrWfY',
    appId: '1:625297648979:android:0524ae53c2d36f742d85a6',
    messagingSenderId: '625297648979',
    projectId: 'adroit-hall-451612-t1',
    storageBucket: 'adroit-hall-451612-t1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpKsS5WRhWftB-ofQVb9nCA28e3l0C0rg',
    appId: '1:625297648979:ios:fb41eafc154930ad2d85a6',
    messagingSenderId: '625297648979',
    projectId: 'adroit-hall-451612-t1',
    storageBucket: 'adroit-hall-451612-t1.firebasestorage.app',
    iosClientId: '625297648979-sbb45lhkek29fh46jejeut3d5cmourt9.apps.googleusercontent.com',
    iosBundleId: 'com.starsky.snapstar',
  );
}
